CREATE TABLE tbl_provinsi(
   id            INTEGER  NOT NULL PRIMARY KEY 
  ,Nama_provinsi VARCHAR(29) NOT NULL
);
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (1,'Aceh');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (2,'Sumatra Utara');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (3,'Sumatra Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (4,'Riau');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (5,'Jambi');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (6,'Sumatra Selatan');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (7,'Bengkulu');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (8,'Lampung');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (9,'Kepulauan Bangka Belitung');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (10,'Kepulauan Riau');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (11,'Daerah Khusus Ibukota Jakarta');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (12,'Jawa Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (13,'Jawa Tengah');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (14,'Daerah Istimewa Yogyakarta');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (15,'Jawa Timur');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (16,'Banten');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (17,'Bali');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (18,'Nusa Tenggara Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (19,'Nusa Tenggara Timur');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (20,'Kalimantan Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (21,'Kalimantan Tengah');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (22,'Kalimantan Selatan');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (23,'Kalimantan Timur');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (24,'Kalimantan Utara');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (25,'Sulawesi Utara');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (26,'Sulawesi Tengah');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (27,'Sulawesi Selatan');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (28,'Sulawesi Tenggara');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (29,'Gorontalo');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (30,'Sulawesi Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (31,'Maluku');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (32,'Maluku Utara');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (33,'Papua');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (34,'Papua Barat');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (35,'Papua Selatan');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (36,'Papua Tengah');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (37,'Papua Pegunungan');
INSERT INTO tbl_provinsi(id,Nama_provinsi) VALUES (38,'Papua Barat Daya');
