CREATE TABLE tbl_peternakan(
   id                INTEGER  NOT NULL PRIMARY KEY 
  ,id_provinsi       INTEGER  NOT NULL
  ,alamat_peternakan VARCHAR(63) NOT NULL
  ,nama_peternakan   VARCHAR(38) NOT NULL
  ,no_telp           VARCHAR(13)
  ,created_at        VARCHAR(4)
  ,updated_at        VARCHAR(4)
  ,FIELD8            VARCHAR(30)
  ,FIELD9            VARCHAR(30)
  ,FIELD10           VARCHAR(30)
);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (1,4,'Jl. Raya Blotongan No. 123','ABON ABADI','0298 - 327646',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (2,18,'Jl. Jend Sudirman No. 339','ABON JUARA JUARA FOOD INDUSTRI','0298 - 324060',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (3,1,'Jl. Bhumimas Raya Desa Talaga','ADIL MART, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (4,6,'Karto Darmo','AGUS SP',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (5,15,'Jl. Raya Sigandu','AJ FILET',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (6,23,'Wonosari Tengah Raya','AL BAROKAH CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (7,10,'Jl. Raya Margaluyu No. 402','ANDHIKA PAKAN TERNAK,CV','0265 - 311489',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (8,12,'Jl. Jababeka Ii Tob Blok C No.16 V Kawasan Indi Jababeka I','ARLENE JAYAMANDIRI, PT','021 - 893544',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (9,28,'Kampung Kalurahan','ASIA AFRIKA, PT','021 - 982896',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (10,37,'Desa Krembung Rt.07/04','AYAM GORENG ARIFIN','031 - 885023',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (11,16,'Jl. Cijeungjing','AYAM POTONG BAROKAH',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (12,16,'Kp. Setiajaya','AYAM POTONG CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (13,21,'Perum Pesona Rajawali','AYUDYA JAYA ABADI, CV','0361 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (14,36,'Jl. Bumi Mas Raya No. 5 Kawasan Industri Cikupamas','BANGKIT SETIA SENTOSA PRIMATAMA, PT','021 - 594030',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (15,30,'Jl. Cantiga Petir Cipondoh','BAROKAH FOOD, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (16,3,'Jl. Raya Randusari Nepen Km. 2','CAHAYA GUNUNG FOODS, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (17,26,'Jl. A.yani Km. 13','CAKRA PERKASA JAYAMULIA, PT','0511 - 422042',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (18,35,'Jl. Raya Jakarta Bogor Km. 51','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (19,22,'Desa Tlajung Udik','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (20,14,'Jl. Industri Iv Kaw. Modern Industri Kav. 6-8','CHAROEN POKHPAND INDONESIA, PT','0254 - 402628',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (21,35,'Jl. Ir Sutami Km. 15','CHAROEN POKPHAND INDONESIA FEEDMILL LA','0721 - 350602',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (22,6,'Jl. Berbek Industri No. 1 No. 24 Berbek','CHAROEN POKPHAND INDONESIA TBK, PT','031 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (23,15,'Jl. Pattimura Km. 1 Kutowinangun Lor','CHAROEN POKPHAND INDONESIA, PT','0298 - 327352',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (24,36,'Dusun V Klumpang Kampung','CIOMAS ADI SATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (25,32,'Jl. Raya Kaba Kaba','CIOMAS ADISATWA BALI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (26,20,'Jl. Raya Sadang-subang Km 14','CIOMAS ADISATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (27,9,'Jl. Patimura Km. 6','CIOMAS ADISATWA, PT','0298 - 342092',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (28,19,'Desa Semambung','CIOMAS INDONESIA, PT/ CIOMAS ADI SATWA','031 - 898629',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (29,18,'Jl. Talaga Mas Raya No. 29','CITRA GUNA LESTARI, PT','021 - 594036',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (30,33,'Kp. Setia Jaya','DAGING AYAM CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (31,19,'Dusun Penampan Wonokoyo','DINAMIKA MEGATAMA CITRA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (32,36,'Desa Luwung','DINAMIKA MEGATAMA CITRA, PT','031 - 848421',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (33,18,'Dusun Penampon','DINAMIKA MEGATAMA CITRA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (34,21,'Jl. Dr. Sitanala Tanah Lapang Kecil','DOK PERKAPALAN WAYAME, PT','0911 - 321674',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (35,14,'Jl. Surya Lestari Kav 1 - 17b Kaw. Surya Cipta','EAST HOPE AGRICULTURE IND., PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (36,36,'Jl. Raya Serang Km. 17 No.19 Kawasan Industri Cikupa Mas','FEPROTAMA PERTIWI, PT','021 - 596903',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (37,26,'Jl. Raya Sigandu Rt. 01/04','FILET IKAN AJ (AYAMTO)',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (38,29,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (39,28,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (40,31,'Jl. Pancasenggang/ Kp. Rancasenggang','GAYAM',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (41,11,'Jl. Raya Tulangan','GELANG TANI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (42,38,'Jl. Raya Gondek 1 A','GEMILANG INTI SUKSES, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (43,5,'Dk Baros Rt 2/ Rw 8','GEMILANG SETIA SEJAHTERA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (44,3,'Jl. Setia Budi Timur 28','HARAPAN AYAM POTONG','0821 - 413210',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (45,25,'Jl. Hati Murni','HARCO, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (46,28,'Jl. Recobarong Iii/41','HARYONO','0355 - 775559',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (47,32,'Kawasan Industri Lippo Cikarang Blok A E-52','HENPRAKAYAMA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (48,21,'Jl. Raya Ciruas Petir Kp. Lebak','HIBER JAYA','0254 - 283095',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (49,16,'Jalan Pangeran Ayin','INDFUSTRI KOPI CAP AYAM, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (50,27,'Jl. Toyogiri','INDO MURAYAMA PRES & DIES INDUSTRI, PT','021 - 880744',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (51,6,'Jl. Raya Blotongan No. 123','ABON ABADI','0298 - 327646',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (52,5,'Jl. Jend Sudirman No. 339','ABON JUARA JUARA FOOD INDUSTRI','0298 - 324060',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (53,24,'Jl. Bhumimas Raya Desa Talaga','ADIL MART, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (54,4,'Karto Darmo','AGUS SP',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (55,27,'Jl. Raya Sigandu','AJ FILET',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (56,23,'Wonosari Tengah Raya','AL BAROKAH CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (57,16,'Jl. Raya Margaluyu No. 402','ANDHIKA PAKAN TERNAK,CV','0265 - 311489',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (58,23,'Jl. Jababeka Ii Tob Blok C No.16 V Kawasan Indi Jababeka I','ARLENE JAYAMANDIRI, PT','021 - 893544',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (59,18,'Kampung Kalurahan','ASIA AFRIKA, PT','021 - 982896',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (60,32,'Desa Krembung Rt.07/04','AYAM GORENG ARIFIN','031 - 885023',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (61,19,'Jl. Cijeungjing','AYAM POTONG BAROKAH',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (62,19,'Kp. Setiajaya','AYAM POTONG CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (63,35,'Perum Pesona Rajawali','AYUDYA JAYA ABADI, CV','0361 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (64,10,'Jl. Bumi Mas Raya No. 5 Kawasan Industri Cikupamas','BANGKIT SETIA SENTOSA PRIMATAMA, PT','021 - 594030',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (65,16,'Jl. Cantiga Petir Cipondoh','BAROKAH FOOD, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (66,32,'Jl. Raya Randusari Nepen Km. 2','CAHAYA GUNUNG FOODS, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (67,18,'Jl. A.yani Km. 13','CAKRA PERKASA JAYAMULIA, PT','0511 - 422042',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (68,19,'Jl. Raya Jakarta Bogor Km. 51','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (69,32,'Desa Tlajung Udik','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (70,5,'Jl. Industri Iv Kaw. Modern Industri Kav. 6-8','CHAROEN POKHPAND INDONESIA, PT','0254 - 402628',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (71,27,'Jl. Ir Sutami Km. 15','CHAROEN POKPHAND INDONESIA FEEDMILL LA','0721 - 350602',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (72,25,'Jl. Berbek Industri No. 1 No. 24 Berbek','CHAROEN POKPHAND INDONESIA TBK, PT','031 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (73,10,'Jl. Pattimura Km. 1 Kutowinangun Lor','CHAROEN POKPHAND INDONESIA, PT','0298 - 327352',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (74,35,'Dusun V Klumpang Kampung','CIOMAS ADI SATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (75,7,'Jl. Raya Kaba Kaba','CIOMAS ADISATWA BALI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (76,29,'Jl. Raya Sadang-subang Km 14','CIOMAS ADISATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (77,28,'Jl. Patimura Km. 6','CIOMAS ADISATWA, PT','0298 - 342092',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (78,2,'Desa Semambung','CIOMAS INDONESIA, PT/ CIOMAS ADI SATWA','031 - 898629',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (79,1,'Jl. Talaga Mas Raya No. 29','CITRA GUNA LESTARI, PT','021 - 594036',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (80,19,'Kp. Setia Jaya','DAGING AYAM CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (81,11,'Dusun Penampan Wonokoyo','DINAMIKA MEGATAMA CITRA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (82,10,'Desa Luwung','DINAMIKA MEGATAMA CITRA, PT','031 - 848421',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (83,29,'Dusun Penampon','DINAMIKA MEGATAMA CITRA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (84,36,'Jl. Dr. Sitanala Tanah Lapang Kecil','DOK PERKAPALAN WAYAME, PT','0911 - 321674',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (85,26,'Jl. Surya Lestari Kav 1 - 17b Kaw. Surya Cipta','EAST HOPE AGRICULTURE IND., PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (86,26,'Jl. Raya Serang Km. 17 No.19 Kawasan Industri Cikupa Mas','FEPROTAMA PERTIWI, PT','021 - 596903',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (87,6,'Jl. Raya Sigandu Rt. 01/04','FILET IKAN AJ (AYAMTO)',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (88,5,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (89,26,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (90,28,'Jl. Pancasenggang/ Kp. Rancasenggang','GAYAM',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (91,33,'Jl. Raya Tulangan','GELANG TANI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (92,33,'Jl. Raya Gondek 1 A','GEMILANG INTI SUKSES, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (93,26,'Dk Baros Rt 2/ Rw 8','GEMILANG SETIA SEJAHTERA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (94,2,'Jl. Setia Budi Timur 28','HARAPAN AYAM POTONG','0821 - 413210',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (95,16,'Jl. Hati Murni','HARCO, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (96,11,'Jl. Recobarong Iii/41','HARYONO','0355 - 775559',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (97,27,'Kawasan Industri Lippo Cikarang Blok A E-52','HENPRAKAYAMA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (98,19,'Jl. Raya Ciruas Petir Kp. Lebak','HIBER JAYA','0254 - 283095',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (99,13,'Jalan Pangeran Ayin','INDFUSTRI KOPI CAP AYAM, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (100,10,'Jl. Toyogiri','INDO MURAYAMA PRES & DIES INDUSTRI, PT','021 - 880744',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (101,13,'Jl. Raya Blotongan No. 123','ABON ABADI','0298 - 327646',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (102,16,'Jl. Jend Sudirman No. 339','ABON JUARA JUARA FOOD INDUSTRI','0298 - 324060',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (103,20,'Jl. Bhumimas Raya Desa Talaga','ADIL MART, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (104,10,'Karto Darmo','AGUS SP',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (105,17,'Jl. Raya Sigandu','AJ FILET',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (106,36,'Wonosari Tengah Raya','AL BAROKAH CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (107,2,'Jl. Raya Margaluyu No. 402','ANDHIKA PAKAN TERNAK,CV','0265 - 311489',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (108,20,'Jl. Jababeka Ii Tob Blok C No.16 V Kawasan Indi Jababeka I','ARLENE JAYAMANDIRI, PT','021 - 893544',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (109,11,'Kampung Kalurahan','ASIA AFRIKA, PT','021 - 982896',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (110,30,'Desa Krembung Rt.07/04','AYAM GORENG ARIFIN','031 - 885023',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (111,6,'Jl. Cijeungjing','AYAM POTONG BAROKAH',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (112,23,'Kp. Setiajaya','AYAM POTONG CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (113,17,'Perum Pesona Rajawali','AYUDYA JAYA ABADI, CV','0361 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (114,10,'Jl. Bumi Mas Raya No. 5 Kawasan Industri Cikupamas','BANGKIT SETIA SENTOSA PRIMATAMA, PT','021 - 594030',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (115,31,'Jl. Cantiga Petir Cipondoh','BAROKAH FOOD, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (116,22,'Jl. Raya Randusari Nepen Km. 2','CAHAYA GUNUNG FOODS, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (117,16,'Jl. A.yani Km. 13','CAKRA PERKASA JAYAMULIA, PT','0511 - 422042',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (118,21,'Jl. Raya Jakarta Bogor Km. 51','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (119,24,'Desa Tlajung Udik','CALVIN METAL PRODUCTS, PT','021 - 867053',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (120,37,'Jl. Industri Iv Kaw. Modern Industri Kav. 6-8','CHAROEN POKHPAND INDONESIA, PT','0254 - 402628',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (121,7,'Jl. Ir Sutami Km. 15','CHAROEN POKPHAND INDONESIA FEEDMILL LA','0721 - 350602',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (122,5,'Jl. Berbek Industri No. 1 No. 24 Berbek','CHAROEN POKPHAND INDONESIA TBK, PT','031 -',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (123,35,'Jl. Pattimura Km. 1 Kutowinangun Lor','CHAROEN POKPHAND INDONESIA, PT','0298 - 327352',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (124,38,'Dusun V Klumpang Kampung','CIOMAS ADI SATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (125,34,'Jl. Raya Kaba Kaba','CIOMAS ADISATWA BALI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (126,24,'Jl. Raya Sadang-subang Km 14','CIOMAS ADISATWA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (127,29,'Jl. Patimura Km. 6','CIOMAS ADISATWA, PT','0298 - 342092',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (128,30,'Desa Semambung','CIOMAS INDONESIA, PT/ CIOMAS ADI SATWA','031 - 898629',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (129,12,'Jl. Talaga Mas Raya No. 29','CITRA GUNA LESTARI, PT','021 - 594036',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (130,35,'Kp. Setia Jaya','DAGING AYAM CEMARA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (131,8,'Dusun Penampan Wonokoyo','DINAMIKA MEGATAMA CITRA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (132,30,'Desa Luwung','DINAMIKA MEGATAMA CITRA, PT','031 - 848421',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (133,9,'Dusun Penampon','DINAMIKA MEGATAMA CITRA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (134,11,'Jl. Dr. Sitanala Tanah Lapang Kecil','DOK PERKAPALAN WAYAME, PT','0911 - 321674',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (135,8,'Jl. Surya Lestari Kav 1 - 17b Kaw. Surya Cipta','EAST HOPE AGRICULTURE IND., PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (136,6,'Jl. Raya Serang Km. 17 No.19 Kawasan Industri Cikupa Mas','FEPROTAMA PERTIWI, PT','021 - 596903',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (137,24,'Jl. Raya Sigandu Rt. 01/04','FILET IKAN AJ (AYAMTO)',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (138,7,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (139,21,'Jl. Inspeksi Tarum Barat Pekopen Lambang Jaya Tambun','GALIH AYAM PARAMENT, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (140,18,'Jl. Pancasenggang/ Kp. Rancasenggang','GAYAM',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (141,7,'Jl. Raya Tulangan','GELANG TANI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (142,16,'Jl. Raya Gondek 1 A','GEMILANG INTI SUKSES, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (143,23,'Dk Baros Rt 2/ Rw 8','GEMILANG SETIA SEJAHTERA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (144,20,'Jl. Setia Budi Timur 28','HARAPAN AYAM POTONG','0821 - 413210',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (145,9,'Jl. Hati Murni','HARCO, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (146,37,'Jl. Recobarong Iii/41','HARYONO','0355 - 775559',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (147,38,'Kawasan Industri Lippo Cikarang Blok A E-52','HENPRAKAYAMA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (148,23,'Jl. Raya Ciruas Petir Kp. Lebak','HIBER JAYA','0254 - 283095',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (149,10,'Jalan Pangeran Ayin','INDFUSTRI KOPI CAP AYAM, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (150,29,'Jl. Toyogiri','INDO MURAYAMA PRES & DIES INDUSTRI, PT','021 - 880744',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (151,35,'Pesisir Prenduan','ABD HADI',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (152,25,'Pengaletan Rt.04/06','ABDUL AZIS','852325',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (153,33,'Jalan Gajah Mada Kompleks Tpi','AGAPE CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (154,10,'jl.Taman Mahardika No.28 Mumbul','AGRO MINA DEWATA, CV','777292',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (155,28,'jl.Gatot Subroto Pondok Batu','AGUNG SUMATERA SAMUDERA ABADI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (156,3,'jl.Raya Sigandu','AJ FILET',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (157,29,'jl.Bomo Rejosari Rt01/rw2','AJI/YULIATI, KRUPUK','813364',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (158,8,'Kelurahan Sagerat','ALAM BARU RECORD, PT','812897',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (159,22,'jl.Rungkut Industri Ii/25','ALAM JAYA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (160,8,'jl.Demaga Timur Transit 19 Muara Baru','ALAM SAMUDRA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (161,14,'Madidir Unet','ALIANSI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (162,36,'Kel Madidir Unet','ALLIANCE FOOD INDONESIA INTERNATIONAL,','0438 - 28664',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (163,1,'jl.Jeleduk','ALSTOM POWER ENERGY SYSTEM PT','31 - 3292080',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (164,25,'jl.Pakar Timur Ii No.109','ALUMNI BANDUNG, PT','022 - 250125',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (165,13,'Komplek Ruko Fanindo Blok D No.5','ALUSTEEL ENGINEERING INDONESIA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (166,2,'Desa Tasik Agung No 10','ALVIAN PUTRA, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (167,18,'jl.Raya Bulu Sidokare','AMIN JAYA, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (168,34,'jl.Komp Pps Samudra','AMO (ABADI MAKMUR OCEAN), PT','0401 - 312960',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (169,24,'Dusun Kalimati','ANANTA PRATAMA, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (170,10,'jl.Joyoboyo No.05','ANDALAS, UD','0333 - 423705',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (171,7,'Dusun Bancang Rt.03 Rw.02','ANDI JAYA','878299',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (172,10,'jl.Komp Pps Samudra','ANDIKA, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (173,25,'jl.Raya Sby Malang Km.38','ANEKA TUNA INDONESIA, PT','0343 - 851361',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (174,1,'jl.Gatot Subroto','ANGEL FASHION STUDIO, PT','31 - 8912117',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (175,27,'Dukuhmulyo','ANI MITRA JAYA',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (176,30,'Mandaran Ii Rt.02/06','ANK PUTRA','0336 - 721276',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (177,35,'jl.Jala Iv No.32 Paya Pasir','ANUGERAH ALAM, PD','061 - 685221',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (178,13,'Jl Gosamtian Dusun Marbali','ANUGERAH BAHARI MANDIRI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (179,14,'jl.Bambu Runcing No.99','ANUGERAH BINTANG CEMERLANG, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (180,30,'jl.Letjen Suprapto','ANUGERAH KERAMAT INDAH, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (181,18,'Desa Sobontoro','ANUGERAH LAUT (PENGERINGAN IKAN AL AMI',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (182,35,'Dukuh Rembangan Rt.01/03 Tasikagung','ANUGERAH MINA RAYA, UD','813265',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (183,19,'jl.Gatot Subroto Komplek Ppn','ANUGERAH SARI LAUT, PT','063 - 24428',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (184,21,'Pelabuhan Perikanan Samudera Jakarta Kawasan Dermag','ANUGERAH SECO JAYA, PT','6628039',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (185,33,'jl.Metro Tanjung Bunga A.33 Ruko Sumba Opu','ANUGERAH SEJATI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (186,37,'jl.Nunumahu','ANUGERAH TEHORU MANISE, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (187,27,'Casagardenia','ANUGRAH , UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (188,12,'jl.Nambangan No.9','ANUGRAH ARTA ABADI, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (189,22,'jl.Raya Jompong','ANUGRAH JAYA , UD','0322 - 662069',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (190,15,'Lorong Tanjung Merah','ANUGRAH TIMUR MAKMUR, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (191,27,'Dusun Vii Desa Naga Kisar','AQUA FARM, PT','062 - 41918',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (192,24,'jl.Tambakaji V No.9','AQUAFARM NUSANTARA, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (193,32,'jl.By Pass Ngurah Rai No.92 Xx Pesanggrahan','ARABIKATAMA KHATULISTIWA FI, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (194,14,'Desa Warabal','ARABIKATAMA KHATULISTIWA FISHING INDUS','0917 - 21258',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (195,4,'jl.Rajasam Dobo','ARAFURA FISHING INDUSTRIES, CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (196,33,'jl.Muara Baru Ujung Dermaga Transit No 16','ARIYA JAYA SANTANG, PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (197,16,'Komplek Tpi','ARTA JAYA, UD',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (198,4,'jl.Jendral A.h.Nasution','ARTA MINA JAYA , PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (199,11,'Jln. Ngumban Surbakti','HARI JAYA MANDIRI','0979-12873',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (200,2,'samosit','MAJU BERSAMA','0921-42830',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (201,25,'Jl. A.yani 129','CARMA WIRA JATIM,PT','0343 - 421714',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (202,35,'Jl. Berbek Industri Ii/5','FILL SURYA MEGAH,PT','843197',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (203,14,'Jl. Jagalan','GUNUNG MAS',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (204,24,'Kedungbungkus Rt. 4/2','HEALTH MANUFAKTUR,CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (205,3,'Jl. Alianyang','KECAP CAP KAMBING',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (206,6,'Jl. Letnan Tukiyat Km. 4 Dusun Kedon','KURNIA KULIT ABADI,CV','0293 - 788287',NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (207,12,'Jl. Susanto No.8','LOKA,PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (208,38,'Desa Tanjung Sari','RAJAWALI MUSINDO,PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (209,10,'Jl. Solo Km. 10 Sorogenen 1 No. 17 Purwomartani Rt. 008 Rw. 002','SOLUSKY PT',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (210,30,'Sidorejo Rt. 05 Rw. 04','TAMTO MANDIRI ,CV',NULL,NULL,NULL);
INSERT INTO tbl_peternakan(id,id_provinsi,alamat_peternakan,nama_peternakan,no_telp,created_at,updated_at) VALUES (211,12,'Kemirikebo Girikerto Rt. 02 Rw. 07','UMSKEY,CV',NULL,NULL,NULL);
